### PR TITLE
Add `slogdet` implementation

### LINKED ISSUE #27: implementation of `slogdet` in eagerpy
Would you consider to add or accept a contribution to add and implementation of `slogdet` function (see for ex the [numpy implementation)](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html)?

### PR DESCRIPTION
**Pull request by eserie**
Fixes #27

### CODE REVIEW

**Review by jonasrauber — CHANGES_REQUESTED** [review]
The implementation looks good.

We can almost merge this.

But I'd prefer if you could make a few changes to the tests:
- revert the changes to `compare_allclose`
- see the tests for `topk` regarding multiple return values (simply use a separate test for each return value; would also give a more specific error message)
- add a few more test cases that result in qualitatively different results (e.g., a matrix with a finite logdet)

**Comment by eserie** [comment]
Hi @jonasrauber , thanks for your feedback!
I modified the test as you required.
For the test on real values I considered the examples in the [numpy documentation.](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html).
Let me know if you think something else should be accomodate.

**Comment by jonasrauber** [comment]
@eserie Looks good, but we had a small misunderstanding regarding the third change: no need to manually compare to the reference values (because the decorator does compare everything to numpy anyway). What I meant was that you should just duplicate the two tests (for sign and logdet) to have two for the original matrix you had and two for a matrix with finite logdet (so for simple test functions in the end).

**Comment by eserie** [comment]
@jonasrauber , thanks for the comment.
I factorized a bit the test using pytest fixtures. I hope that this keeps the code enough simple.
Also, I restored the infinite test case.

**Comment by jonasrauber** [comment]
@eserie thanks, that's also a nice solution! 
I have to say, a bit surprised that our custom `compare_all*` decorator and `pytest.mark.parametrize` don't break each other (or, more precisely, that they work together in this order; would make more sense to me if it only works if the `compare_all*`  decorator is the inner one (that turns the function with return value into a test function with asserts) … can you explain why it works the way you implemented it?

**Comment by eserie** [comment]
@jonasrauber, it's true that the test code seems to work for both orders of decorators. When they are used with `pytest.mark.parametrize` as inner decorator I would understand that pytest will generate a list of functions with arguments specified applied, like a `functools.partial` operation. However I do not fully understand the mechanism and we should go in the code of pytest to fully understand how decorators are managed.
Indeed, in the last commit I swapped the order of decorators and it works also. I can let the order you prefer.

**Comment by eserie** [comment]
Thanks for the integration @jonasrauber !

**Pull request merged**
